//PATTREN Q 26 PG 72 WITHOUT LOOP

#include<iostream>
using namespace std;
#define ch 'a'
#define ch2 'e'
#define ch3 'i'
#define ch4 'o'
#define ch5 'u'

void main()
{

	int const n=0,n1=2,n2=4,n3=6,n4=8;

	cout<<"\t"<<ch<<" "<<ch2<<" "<<ch3<<" "<<ch4<<" "<<ch5<<endl; //defined constants
 	cout<<"\t"<<n<<" "<<n1<<" "<<n2<<" "<<n3<<" "<<n4<<endl; //memory constants
	cout<<"\t"<<1<<" "<<3<<" "<<5<<" "<<7<<" "<<9<<endl; //literals constants
}