//PRINT 'DEE' QUES 33 PG 72

#include<iostream>
#include<iomanip>
using namespace std;

void main()
{

	cout<<"\n";
	cout<<"\t DDDD"<<setw(4)<<"E"<<"EEEE"<<setw(3)<<"E"<<"EEEE"<<endl;
	cout<<"\t D"<<setw(4)<<"D"<<setw(3)<<"E"<<setw(7)<<"E"<<endl;
	cout<<"\t D"<<setw(4)<<"D"<<setw(3)<<"E"<<setw(7)<<"E"<<endl;
	cout<<"\t D"<<setw(4)<<"D"<<setw(3)<<"E"<<"EE"<<setw(5)<<"E"<<"EE"<<endl;
	cout<<"\t D"<<setw(4)<<"D"<<setw(3)<<"E"<<setw(7)<<"E"<<endl;
	cout<<"\t D"<<setw(4)<<"D"<<setw(3)<<"E"<<setw(7)<<"E"<<endl;
	cout<<"\t DDDD"<<setw(4)<<"E"<<"EEEE"<<setw(3)<<"E"<<"EEEE"<<endl;

	

	cout<<endl;

}

