// PRINT 'BEF' WITHOUT USING LOOP QUESTION 33 PG 72

#include<iostream>
#include<iomanip>
using namespace std;

void main()

{
	 cout<<"\n";
	 cout<<"\t BBB"<<setw(4)<<"E"<<"EEEE"<<setw(3)<<"F"<<"FFFF"<<endl;
     cout<<"\t B"<<setw(3)<<"B"<<setw(3)<<"E"<<setw(7)<<"F"<<endl;
	 cout<<"\t B"<<setw(3)<<"B"<<setw(3)<<"E"<<setw(7)<<"F"<<endl;
     cout<<"\t BBB"<<setw(4)<<"E"<<"EE"<<setw(5)<<"F"<<"FF"<<endl;
	 cout<<"\t B"<<setw(3)<<"B"<<setw(3)<<"E"<<setw(7)<<"F"<<endl;
	 cout<<"\t B"<<setw(3)<<"B"<<setw(3)<<"E"<<setw(7)<<"F"<<endl;
	 cout<<"\t BBB"<<setw(4)<<"E"<<"EEEE"<<setw(3)<<"F"<<endl;
	


}
