//QUESTION 35 PG 72

#include<iostream>
using namespace std;

void main()
{
	int  n,n1,n2,n3,n4,n5,n6,n7,n8,n9;

	cout<<"\n Please enter 10 integers:";
	cin>>n>>n1>>n2>>n3>>n4>>n5>>n6>>n7>>n8>>n9;

	cout<<"\n Your Numbers are="<<endl;
	cout<<"\t "<<n<<"\t"<<n9<<endl;
	cout<<"\t "<<n1<<"\t"<<n8<<endl;
	cout<<"\t "<<n2<<"\t"<<n7<<endl;
	cout<<"\t "<<n3<<"\t"<<n6<<endl;
	cout<<"\t "<<n4<<"\t"<<n5<<endl;

	cout<<endl;

	cout<<"\n Size of int="<<(sizeof(int));
}