//QUESTION 37

#include<iostream>
#include<iomanip>
using namespace std;

void main()
{
	int  n,n1,n2,n3,n4,n5,n6,n7,n8;

	cout<<"\n Please enter 9 integers:";
	cin>>n>>n1>>n2>>n3>>n4>>n5>>n6>>n7>>n8;

	cout<<"\n Your Numbers are="<<endl;
	cout<<setw(5)<<n<<setw(5)<<n1<<setw(5)<<n2<<endl;
	cout<<setw(5)<<n3<<setw(5)<<n4<<setw(5)<<n5<<endl;
	cout<<setw(5)<<n6<<setw(5)<<n7<<setw(5)<<n8<<endl;


	cout<<endl;

}